name = "MandelMakie"
uuid = "e18c8c28-cd4b-4c7c-875d-43a19c5cccb0"
authors = ["vambrosi <vambrosi@indiana.edu>"]
version = "0.1.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
# Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
