name = "MandelGtk"
uuid = "61a4d709-07bc-4d87-825b-e807dca3b60b"
authors = ["Vinicius Ambrosi <vambrosi@indiana.edu>"]
version = "0.1.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
Gtk4 = "9db2cae5-386f-4011-9d63-a5602296539b"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Crayons = "4.1.1"
HypertextLiteral = "0.9.5"
